version: "3.9"
services:
  postgres_db:
    image: postgres:14-alpine
    container_name: member_service_postgres
    restart: always
    environment:
      - POSTGRES_USER = *******
      - POSTGRES_PASSWORD = *******
      - POSTGRES_DB= Member
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: