# Step 1: Test
FROM golang:latest AS tester

ARG GITHUB_TOKEN

ENV GOPRIVATE=github.com/iamsad5566/*

RUN apt-get update && apt-get install -y git
RUN echo "machine github.com login $GITHUB_TOKEN password x-oauth-basic" > ~/.netrc

WORKDIR /app
RUN git clone https://github.com/iamsad5566/setconf.git
RUN ls ./setconf
RUN cp ./setconf/config.yml .
COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go test ./...