name: auto test

on:
    push:
      branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Committed in the open-source version
      - name: Set up GOPRIVATE
        run: echo "GOPRIVATE=github.com/iamsad5566/*" >> $GITHUB_ENV

      - name: Log in to GitHub Package Registry
        run: echo ${{ secrets.TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        
      - name: Clone repository 
        run: git clone https://github.com/iamsad5566/member_service_frame.git
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'
        id: go
      
      - name: CD to the cloned repository
        run: cd member_service_frame

      - name: Unit test
        run: go test -v ./... -coverprofile=coverage.out -covermode=atomic

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          flags: smart-tests
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
