name: auto test

on:
    push:
      branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'
        id: go

      # Committed in the open-source version of the repository
      - name: Clone repository 
        run: git clone https://github.com/iamsad5566/member_service_frame.git
      
      - name: private repo
        run: go env -w GOPRIVATE=github.com/iamsad5566/*

      - name: check folder
        run: ls -la
     
      - name: login github
        run: |
          echo machine github.com login ${{ secrets.TOKEN }} password x-oauth-basic > ~/.netrc

      - name: unit test
        run: |
          cd member_service_frame
          go test -v ./... -coverprofile=coverage.out -covermode=atomic

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          flags: smart-tests
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
